/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.thongke;

import controller.ThongKeController;
import javax.swing.JPanel;

/**
 *
 * @author DELL
 */
public class ThongKePanel extends javax.swing.JPanel {

    /**
     * Creates new form ThongKePanel
     */
    private static ThongKePanel instance;
    
    public ThongKePanel(JPanel panMainThongKe) {
        initComponents();
        setBounds(0, 0, 710, 442);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableJpn = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tuTuoiJtf = new javax.swing.JTextField();
        denTuoiJtf = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ShowButton = new javax.swing.JButton();
        GenderJcb = new javax.swing.JComboBox<>();
        StatusJcb = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        textCount = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableJpn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã Định Danh", "Họ Tên", "Ngày Sinh", "Giới Tính", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableJpn);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 162, 690, 120));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Tình trạng :");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, 30));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Độ tuổi    :");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 30));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Từ:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, 30));

        tuTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(tuTuoiJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 51, 30));

        denTuoiJtf.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        add(denTuoiJtf, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 51, 30));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("=>");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, -1, 30));

        jLabel5.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jLabel5.setText("Tuổi");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 30));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Giới tính :");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 30));

        ShowButton.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ShowButton.setText("Show");
        ShowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowButtonActionPerformed(evt);
            }
        });
        add(ShowButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 20, 105, 30));

        GenderJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        GenderJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Nam", "Nữ" }));
        add(GenderJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 90, 30));

        StatusJcb.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        StatusJcb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Toàn bộ", "Thường trú", "Tạm trú", "Tạm vắng" }));
        add(StatusJcb, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 158, 30));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("Số lượng :");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 120, -1, -1));
        add(textCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 40, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void ShowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowButtonActionPerformed
        // TODO add your handling code here:
        new ThongKeController().ThongKe(tableJpn, GenderJcb, StatusJcb, tuTuoiJtf, denTuoiJtf, textCount);
    }//GEN-LAST:event_ShowButtonActionPerformed

     public static ThongKePanel getInstance(JPanel panMainThongKe) {
		if(instance == null) {
			instance = new ThongKePanel(panMainThongKe);
		}
		return instance;
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GenderJcb;
    private javax.swing.JButton ShowButton;
    private javax.swing.JComboBox<String> StatusJcb;
    private javax.swing.JTextField denTuoiJtf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableJpn;
    private javax.swing.JTextField textCount;
    private javax.swing.JTextField tuTuoiJtf;
    // End of variables declaration//GEN-END:variables
}
